import { AvailabilityCreateNestedManyWithoutEventTypesInput } from "./AvailabilityCreateNestedManyWithoutEventTypesInput";
import { InputJsonValue } from "../../types";
import { EventTypeCustomInputCreateNestedManyWithoutEventTypesInput } from "./EventTypeCustomInputCreateNestedManyWithoutEventTypesInput";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { ScheduleWhereUniqueInput } from "../schedule/ScheduleWhereUniqueInput";
import { UserCreateNestedManyWithoutEventTypesInput } from "./UserCreateNestedManyWithoutEventTypesInput";
import { WebhookCreateNestedManyWithoutEventTypesInput } from "./WebhookCreateNestedManyWithoutEventTypesInput";
import { WorkflowsOnEventTypeCreateNestedManyWithoutEventTypesInput } from "./WorkflowsOnEventTypeCreateNestedManyWithoutEventTypesInput";

export type EventTypeCreateInput = {
  afterEventBuffer: number;
  availability?: AvailabilityCreateNestedManyWithoutEventTypesInput;
  beforeEventBuffer: number;
  bookings?: InputJsonValue;
  currency: string;
  customInputs?: EventTypeCustomInputCreateNestedManyWithoutEventTypesInput;
  description?: string | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  disableGuests: boolean;
  eventName?: string | null;
  hashedLink?: number | null;
  hidden: boolean;
  hideCalendarNotes: boolean;
  length: number;
  locations?: InputJsonValue;
  metadata?: InputJsonValue;
  minimumBookingNotice: number;
  periodCountCalendarDays?: boolean | null;
  periodDays?: number | null;
  periodEndDate?: Date | null;
  periodStartDate?: Date | null;
  periodType: "UNLIMITED" | "ROLLING" | "RANGE";
  position: number;
  price: number;
  recurringEvent?: InputJsonValue;
  requiresConfirmation: boolean;
  schedule?: ScheduleWhereUniqueInput | null;
  schedulingType?: "ROUND_ROBIN" | "COLLECTIVE" | null;
  seatsPerTimeSlot?: number | null;
  slotInterval?: number | null;
  slug: string;
  successRedirectUrl?: string | null;
  team?: number | null;
  timeZone?: string | null;
  title: string;
  userId?: number | null;
  users?: UserCreateNestedManyWithoutEventTypesInput;
  webhooks?: WebhookCreateNestedManyWithoutEventTypesInput;
  workflows?: WorkflowsOnEventTypeCreateNestedManyWithoutEventTypesInput;
};
